# Generated by Django 4.2 on 2024-11-14 19:26

import bot.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full name')),
                ('full_name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('full_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('username_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('username_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, validators=[bot.validators.phone_number_validator])),
                ('user_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='telegram username')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
