# Generated by Django 4.2 on 2024-11-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
    ]
