# Generated by Django 4.2 on 2024-11-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_order_address_ru_order_address_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('delivery_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='Order items in JSON format'),
        ),
    ]
