# Generated by Django 4.2 on 2024-11-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_order_options_alter_cartitem_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMinSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_sum', models.CharField(max_length=255, verbose_name='order minimum sum')),
            ],
            options={
                'verbose_name': 'Order minimum sum',
                'verbose_name_plural': 'Order minimum sum',
            },
        ),
    ]
