# Generated by Django 4.2 on 2024-11-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_orderminsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders_receipts/', verbose_name='Order Image'),
        ),
    ]
