# Generated by Django 4.2 on 2024-11-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_order_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='image',
            new_name='receipt_image',
        ),
    ]
