# Generated by Django 4.2 on 2024-11-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_cartitem_product_alter_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt_image',
        ),
    ]
