# Generated by Django 4.2 on 2024-11-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
