# Generated by Django 4.2 on 2024-11-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_state_options_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='county',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
