# Generated by Django 4.2 on 2024-11-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_customuser_county_customuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uz',
        ),
    ]
