# Generated by Django 4.2 on 2024-11-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('YARATILGAN', 'YARATILGAN'), ("TO'LLANGAN", "TO'LLANGAN"), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='YARATILGAN', max_length=20),
        ),
    ]
