# Generated by Django 4.2 on 2024-11-24 09:14

import bot.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full name')),
                ('full_name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('full_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('username_uz', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('username_ru', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, validators=[bot.validators.phone_number_validator])),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
