# Generated by Django 4.2 on 2024-11-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='delivery_time'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='delivery_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(max_length=100, verbose_name='delivery_time'),
        ),
    ]
