# Generated by Django 4.2 on 2024-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_product_delivery_time_ru_product_delivery_time_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
